from typing import Literal

def parallel(num_threads: int | None = None): ...
def prange(start: int = 0, stop: int | None = None, step: int = 1, nogil: bool = False, schedule: Literal['static', 'dynamic', 'guided', 'runtime'] | None = None, chunksize: int | None = None, num_threads: int | None = None): ...
def threadid() -> int: ...
